Keep popularity statistics on emojis
DaniDiscord/Dani-Server-Utils pull request #35
Opened 2023-06-18 13:01 UTC by jnlt3

Keeps track of the relative popularity of all community emojis. 
An emoji can be counted as "used" every 15 minutes and the amount an emoji used drops by 10% every day in order to take recency into account.
These statistics can later be used to remove community emojis that aren't used.

2024-02-16 19:48 UTC, 3vilN355 requested changes

2024-02-16 19:48 UTC, 3vilN355 commented on src/lib/client.ts
> +      }));
Read and implement [this stackoverflow answer](https://stackoverflow.com/a/49830816) instead.

2024-02-16 19:48 UTC, 3vilN355 commented on src/lib/client.ts
> +    });
What? Why are we `.filter`-ing but having the return of the filter be an object? This won't filter the output at all. Did you intend to `.map`?

2024-02-16 19:48 UTC, 3vilN355 commented on src/lib/stats.ts
> +const regex = new RegExp(`:[a-zA-Z1-9_]+${emojiSuffix}:`);
Has this regex been tested to work on `message.content`? I believe emojis in message contents are formatted quite differently (`<:${emojiName}:${emojiId}>`)

2024-02-16 19:48 UTC, 3vilN355 commented on src/models/EmojiUsage.ts
> +});
Why is the default for `count` 1, when above it was `0` within the `addEmoji` function?
Also, why is the lastUsage a Number and not a Date? (timestamp? messageId? idk)

2024-02-16 19:50 UTC, 3vilN355 commented on src/lib/stats.ts
> +const regex = new RegExp(`:[a-zA-Z1-9_]+${emojiSuffix}:`);
I'm realizing now that it would match that pattern, so it should be fine.

2026-04-21 19:53 UTC, willbyers1 approved these changes

2026-04-21 20:16 UTC, closed without merging